### PR TITLE
Center the alert icon

### PR DESCRIPTION
**Pull request by Jmunapo**
A bit off to the top

Screenshot from 2020-07-27 09-59-02

Centered
Screenshot from 2020-07-27 09-58-46

### CODE REVIEW

**Comment by nandi95** [comment]
Thanks for your contribution.

I don't see any change to the position in the provided picture or when the style rule is toggled in the inspector, nor it should given that this is an absolute positioned item.

Am I missing something? @Jmunapo

**Comment by Jmunapo** [comment]
If you look really close I think about 2px off

**Comment by nandi95** [comment]
Oh yes you're right, I can see now on the picture however on mac/windows in chrome/safari/firefox/edge I can't see any issues with the positioning.

Can you please me know what you have used?
The picture doesn't seem like it's the standard styling or the background being from the demo site, could your styles possibly interfere with the plugin ones?
Is this displacement also happening on a fresh install of the demo site?
@Jmunapo

**Comment by nandi95** [comment]
@Jmunapo Is this still an issue?
See my previous comment.

**Comment by Jmunapo** [comment]
Not anymore, thanks. 😀

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
